---
# This playbook deploys JFrog Mission Control!

- hosts: taget_host
  remote_user: taget_user
  vars_files:
    - vars/main.yml

  tasks:
    - name: Check if Mission Control is installed
      command: "rpm -q jfrog-mission-control"
      # Always run in normal mode
      check_mode: no
      register: rpm_check
      # Force the annoying change message to go away
      changed_when: no
      failed_when: rpm_check.rc > 1


    - name: Download JFrog Mission Control
      command: "wget -q -O {{mc_archive}} {{download_url}} creates={{mc_archive}}"
      # Download JFrog Mission Control if not installed yet
      when: rpm_check.rc != 0

    - name: Install Mission Control through rpm
      command: "sudo rpm -ihv {{mc_archive}}"
      # rpm_check.rc is 0 if installed
      when: rpm_check.rc != 0

    - name: Clean up
      file: state=absent path={{mc_archive}}
