---
# This playbooks configures the default file for Artifactory

- name: Artifactory | Config etc/default file
  template: src=./roles/artifactory/templates/default dest=/var/opt/jfrog/artifactory/etc/
  # To do: notify: restart artifactory
  tags:
    - config-default
