---
# This playbook deploys Jfrog Artifactory!

- hosts: artifactory
  vars_files:
    - vars/main.yml
    - vars/private.yml
  user: $global_user
  sudo: $global_use_sudo
  roles:
    - java
  tasks:
    - include: tasks/main.yml

  handlers:
    - include: handlers/main.yml