---
# This playbook deploys mongodb to CentOS 7 /Red Hat 7
# Reference: https://github.com/Vinelab/ansible-docker.git
- hosts: docker-host
  remote_user: user
  become: yes
  become_method: sudo
  vars_files:
    - vars/main.yml

  tasks:
    - name: Check if docker-ce is installed
      command: "rpm -q docker-ce"
      # Always run in normal mode
      check_mode: no
      register: rpm_check
      # Force the annoying change message to go away
      changed_when: no
      failed_when: rpm_check.rc > 1

    - name: Remove old versions of Docker
      yum: pkg={{item}} state=absent
      with_items:
        - docker
        - docker-common
        - container-selinux
        - docker-selinux
        - docker-engine
    - name: Install yum-utils
      yum: name=yum-utils state=present
      tags: docker
      when: rpm_check.rc != 0

    - name: Install device-mapper-persistent-data
      yum: name=device-mapper-persistent-data state=present
      tags: docker
      when: rpm_check.rc != 0

    - name: Install lvm2
      yum: name=lvm2 state=present
      tags: docker
      when: rpm_check.rc != 0

    - name: Set up the Docker CE repository
      command: "{{ item }}"
      with_items:
        - "yum-config-manager --add-repo {{redhat_docker_repo}}"
        - 'yum makecache fast'
      when: rpm_check.rc != 0

    - name: Install policycoreutils-python
      yum: name=policycoreutils-python state=present
      tags: docker
      when: rpm_check.rc != 0
      
    # This container-selinux needs to be manual installed from the following command
    # You can download it from 
    # ftp://ftp.icm.edu.pl/vol/rzm6/linux-centos-vault/7.3.1611/extras/x86_64/Packages

    - name: Install latest version of docker CE
      yum: name=docker-ce state=present
      tags: docker
      when: rpm_check.rc != 0

    - name: Start docker
      command: systemctl start docker
      tags: docker
      when: rpm_check.rc != 0