---
# This playbook deploys mongodb to CentOS 7

- hosts: mongodb_host
  vars_files:
    - vars/main.yml

  tasks:
    - name: Check if MongoDB is installed
      command: "rpm -q mongodb-org-server"
      # Always run in normal mode
      check_mode: no
      register: rpm_check
      # Force the annoying change message to go away
      changed_when: no
      failed_when: rpm_check.rc > 1

    - name: Add MongoDB yum repo file
      template: "src=mongodb-{{mongodb_version}}-repo.j2 dest=/etc/yum.repos.d/mongodb-{{mongodb_version}}.repo"
      tags: mongodb
      when: rpm_check.rc != 0

    - name: Install MongoDB
      yum: name=mongodb-org state=present
      tags: mongodb
      when: rpm_check.rc != 0




