---
# This playbook deploys nodejs CentOS 7

- hosts: nodejs_host
  vars_files:
    - vars/main.yml

  tasks:
    - name: Check if nodejs is installed
      command: "npm -version"
      # Always run in normal mode
      check_mode: no
      register: rpm_check
      # Force the annoying change message to go away
      changed_when: no
      failed_when: rpm_check.rc > 1

    - name: Install NodeJS repo
      # Just because 6.x is recommended
      command: "curl --silent --location https://rpm.nodesource.com/setup_6.x | bash -"
      when: rpm_check.rc != 0

    - name: Install nodeJs
      yum: name=nodejs state=present
      tags: nodejs
      when: rpm_check.rc != 0