---
# This playbook deploys JFrog Artifactory!

- hosts: target_server (please change)
  become_user: remote_user (please change)
  become_method: sudo
  vars_files:
    - vars/main.yml

  tasks:
    - name: Check of Artifactory is installed
      command: "rpm -q jfrog-artifactory"
      # Always run in normal mode
      check_mode: no
      register: rpm_check
      # Force the annoying change message to go away
      changed_when: no
      failed_when: rpm_check.rc > 1

    - name: Download JFrog Mission Control
      command: "wget -q -O {{artifactory_archive}} {{download_url}} creates={{artifactory_archive}}"
      # Download JFrog Artifactory if not installed yet
      when: rpm_check.rc != 0

    - name: Install Artifactory through rpm
      command: "rpm -ihv {{artifactory_archive}}"
      become: true
      become_method: sudo
      # rpm_check.rc is 0 if installed
      when: rpm_check.rc != 0

    - name: Clean up
      file: state=absent path={{artifactory_archive}}