---
- hosts: artifactory_server
  remote_user:
  sudo: yes
  vars:
    download_url: java_download_url
    download_folder: /opt
    java_name: "{{{{download_folder}}/jdk-8u131-linux-x64.tar.gz}}"
    java_archive: "{{download_folder}}/jdk-8u131-linux-x64.tar.gz"
